<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ip-192-168-2-48.ec2.internal" ignored="0" name="LoginTest" tests="3" failures="1" timestamp="31 Jan 2019 17:43:19 GMT" time="18.524" errors="0">
  <testcase name="invalidLoginTest_InvalidUserNameInvalidPassword" time="7.191" classname="tests.LoginTests"/>
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="3.1" classname="tests.LoginTests">
    <skipped/>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
  <testcase name="invalidLoginTest_EmptyUserEmptyPassword" time="3.261" classname="tests.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]">
      <![CDATA[java.lang.AssertionError: expected [WRONG MESSAGE FOR FAILURE!] but found [Bu alan覺n doldurulmas覺 zorunludur.]
at pages.LoginPage.verifyLoginPassword_aroundBody4(LoginPage.java:43)
at pages.LoginPage$AjcClosure5.run(LoginPage.java:1)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at pages.LoginPage.verifyLoginPassword(LoginPage.java:43)
at tests.LoginTests.invalidLoginTest_EmptyUserEmptyPassword(LoginTests.java:82)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- invalidLoginTest_EmptyUserEmptyPassword -->
</testsuite> <!-- LoginTest -->
